#!/bin/bash
set -ue

DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

# shellcheck disable=SC1090
. "$DIR/../lib/shared.bash"

paths=( $(plugin_read_list CACHED_FOLDERS) )

for path in "${paths[@]}"
do
  # if the path is bad - skip it, don't break things
  if [[ -d ${path} ]]; then
    filename=`echo ${path} |sed 's/\//_/g'`

    # remove trailing '-' from filename
    if [[ ${filename: -1} == "_" ]]; then
      filename=${filename::${#filename}-1}
    fi

    chmod 600 ${path}

    echo "--- compressing ${path}"
    sudo tar -czfp ${filename}.tar.gz ${path}

    # remove '/' as it breaks S3 pathing
    # remove ' ' as it breaks aws s3 cp command
    label=${BUILDKITE_LABEL//\//}
    label=${label// /_}

    s3_bucket="s3://${BUILDKITE_PLUGIN_CACHE_S3_BUCKET}/${BUILDKITE_PIPELINE_SLUG}/${label}"

    echo "--- cp ${filename}.tar.gz into :aws: :amazon-s3:"
    aws s3 cp "${filename}.tar.gz" "${s3_bucket}/${filename}.tar.gz"
  else
    echo "--- skipping, ${path} is not a directory"
  fi
done
