#!/bin/bash

DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

# shellcheck disable=SC1090
. "$DIR/../lib/shared.bash"

paths=( $(plugin_read_list CACHED_FOLDERS) )

for path in "${paths[@]}"
do
  filename=`echo ${path} |sed 's/\//_/g'`

  # remove trailing '-' from filename
  if [[ ${filename: -1} == "_" ]]; then
    filename=${filename::${#filename}-1}
  fi

  # remove '/' as it breaks S3 pathing
  # remove ' ' as it breaks aws s3 cp command
  label=${BUILDKITE_LABEL//\//}
  label=${label// /_}

  s3_bucket="s3://${BUILDKITE_PLUGIN_CACHE_S3_BUCKET}/${BUILDKITE_PIPELINE_SLUG}/${label}"

  aws s3 ls ${s3_bucket}/${filename}.tar.gz
  rc=$?
  if [[ ${rc} -eq 0 ]]; then
    echo "--- :aws: :amazon-s3: cp ${filename}"
    aws s3 cp "${s3_bucket}/${filename}.tar.gz" "."
    
    echo "--- untar into ${path}"
    tar -xzfp ${filename}.tar.gz
  else 
    echo "-- skipping :aws: :amazon-s3: cp as ${filename}.tar.gz does not exist in ${s3_bucket}"
  fi
done
